/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.geepawhill.rwc

class Client {
    val greeting: String
        get() {
            return "Hello world."
        }
}
