/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.geepawhill.rwu

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        println("I WAS CALLED.")
        assertThat(classUnderTest.someLibraryMethod()).isTrue()
    }
}
