/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.geepawhill.rws

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class ServerTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertThat(classUnderTest.greeting).isEqualTo( "Hello world.")
    }
}
