/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.geepawhill.rws

import org.geepawhill.rwu.Library

class Server {
    val greeting: String
        get() {
            return "Hello world."
        }

    // Proof that we depend successfully on rwu
    val library = Library()
}

fun main(args: Array<String>) {
    println(Server().greeting)
}
