name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '15'
    - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    - name Gradle Test
        run: ./gradlew test
